---
title: "README"
author: "Mike Breen"
date: "9 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## run_analysis.R

This script performs the anaylsis on the un-tidy dataset that can be found in https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

The script take no inputs from R but relies on the unzipped data being available in the 
users R Home directory.

The script will combine the test and train datasets with their peripheral files (like variable names 
and actvity description strings in other files) before extracting the mean and standard deviation data.
The script will then create 2 dataframes: 1 with the mean of all the variables previously mentioned per
subject (ave.subject) and another with the mean of the variables per activity (ave.activity).

The script will then create 2 .csv files for these dataframes (in the R Home directory) with the names:
* ave.activity.csv (for the mean of variables per actvity) 
and 
* ave.subject.csv (for the mean of variables per subject).


